In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('iris.csv',names = ['SL','SW','PL','PW'])

In [3]:
data.head()

      SL   SW   PL           PW
5.1  3.5  1.4  0.2  Iris-setosa
4.9  3.0  1.4  0.2  Iris-setosa
4.7  3.2  1.3  0.2  Iris-setosa
4.6  3.1  1.5  0.2  Iris-setosa
5.0  3.6  1.4  0.2  Iris-setosa

In [4]:
X = data[['SW','PL']]

In [6]:
X

      SW   PL
5.1  1.4  0.2
4.9  1.4  0.2
4.7  1.3  0.2
4.6  1.5  0.2
5.0  1.4  0.2
5.4  1.7  0.4
4.6  1.4  0.3
5.0  1.5  0.2
4.4  1.4  0.2
4.9  1.5  0.1
5.4  1.5  0.2
4.8  1.6  0.2
4.8  1.4  0.1
4.3  1.1  0.1
5.8  1.2  0.2
5.7  1.5  0.4
5.4  1.3  0.4
5.1  1.4  0.3
5.7  1.7  0.3
5.1  1.5  0.3
5.4  1.7  0.2
5.1  1.5  0.4
4.6  1.0  0.2
5.1  1.7  0.5
4.8  1.9  0.2
5.0  1.6  0.2
5.0  1.6  0.4
5.2  1.5  0.2
5.2  1.4  0.2
4.7  1.6  0.2
..   ...  ...
6.9  5.7  2.3
5.6  4.9  2.0
7.7  6.7  2.0
6.3  4.9  1.8
6.7  5.7  2.1
7.2  6.0  1.8
6.2  4.8  1.8
6.1  4.9  1.8
6.4  5.6  2.1
7.2  5.8  1.6
7.4  6.1  1.9
7.9  6.4  2.0
6.4  5.6  2.2
6.3  5.1  1.5
6.1  5.6  1.4
7.7  6.1  2.3
6.3  5.6  2.4
6.4  5.5  1.8
6.0  4.8  1.8
6.9  5.4  2.1
6.7  5.6  2.4
6.9  5.1  2.3
5.8  5.1  1.9
6.8  5.9  2.3
6.7  5.7  2.5
6.7  5.2  2.3
6.3  5.0  1.9
6.5  5.2  2.0
6.2  5.4  2.3
5.9  5.1  1.8

[150 rows x 2 columns]

In [9]:
y = data [['PW']]

In [10]:
y

                 PW
5.1     Iris-setosa
4.9     Iris-setosa
4.7     Iris-setosa
4.6     Iris-setosa
5.0     Iris-setosa
5.4     Iris-setosa
4.6     Iris-setosa
5.0     Iris-setosa
4.4     Iris-setosa
4.9     Iris-setosa
5.4     Iris-setosa
4.8     Iris-setosa
4.8     Iris-setosa
4.3     Iris-setosa
5.8     Iris-setosa
5.7     Iris-setosa
5.4     Iris-setosa
5.1     Iris-setosa
5.7     Iris-setosa
5.1     Iris-setosa
5.4     Iris-setosa
5.1     Iris-setosa
4.6     Iris-setosa
5.1     Iris-setosa
4.8     Iris-setosa
5.0     Iris-setosa
5.0     Iris-setosa
5.2     Iris-setosa
5.2     Iris-setosa
4.7     Iris-setosa
..              ...
6.9  Iris-virginica
5.6  Iris-virginica
7.7  Iris-virginica
6.3  Iris-virginica
6.7  Iris-virginica
7.2  Iris-virginica
6.2  Iris-virginica
6.1  Iris-virginica
6.4  Iris-virginica
7.2  Iris-virginica
7.4  Iris-virginica
7.9  Iris-virginica
6.4  Iris-virginica
6.3  Iris-virginica
6.1  Iris-virginica
7.7  Iris-virginica
6.3  Iris-virginica
6.4  Iris-virginica
6.0  Iris-virginica
6.9  Iris-virginica
6.7  Iris-virginica
6.9  Iris-virginica
5.8  Iris-virginica
6.8  Iris-virginica
6.7  Iris-virginica
6.7  Iris-virginica
6.3  Iris-virginica
6.5  Iris-virginica
6.2  Iris-virginica
5.9  Iris-virginica

[150 rows x 1 columns]

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
knn = KNeighborsClassifier()

In [16]:
knn.fit(X,y)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [17]:
testdata = [[2.6, 6.0]]

In [18]:
test = pd.DataFrame(testdata)

In [19]:
print(knn.predict(test))

['Iris-virginica']